version: '3.4'

services:
  calculajuros.api:
    image: calculajurosapi
    ports:
      - "5080:443"
    build:
      context: .
      dockerfile: CalculaJuros/Dockerfile
  taxajuros.api:
    image: taxajurosapi
    ports:
      - "5040:443"
    build:
      context: .
      dockerfile: TaxaJuros/Dockerfile
